// <auto-generated />
namespace PriceLists_Redactor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CellonlyColumnIdnullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CellonlyColumnIdnullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202101300928574_Cell only ColumnId nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
